include_recipe '../../cookbooks/docker'
include_recipe '../../cookbooks/mosh'
include_recipe '../../cookbooks/fish'
include_recipe '../../cookbooks/ruby'
include_recipe '../../cookbooks/vim'
include_recipe '../../cookbooks/aws-cli'
include_recipe '../../cookbooks/bat'
